[package]
name = "multithreaded_pi_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.19.1"
clap = "4.1.8"
difference = { git = "https://github.com/johannhof/difference.rs" }
